### ISSUE TITLE
Flame II enchantment on fortress loot books

### ISSUE THREAD

**Issue by skrollas** [YUNG-GANG/YUNGs-Better-Fortresses#1]
There are occasionally enchanted books on invisible item frames on shelves in the lower part of the fortress. I found a book that has a Flame II enchantment on it. This enchantment is not possible in vanilla, as Flame only has one level normally.

Version: 1.19.2-Forge-1.0.3

![2023-02-24_22 58 14](https://user-images.githubusercontent.com/51177925/221343534-d9e57793-2245-4bb5-b637-781074b8e4e8.png)
![2023-02-24_22 58 21](https://user-images.githubusercontent.com/51177925/221343537-5c3601ad-d2b1-4b15-931c-ea5d530b61b8.png)

**Comment by yungnickyoung** [comment]
Thanks for the report! Next release will have this fixed.
