### ISSUE TITLE
log spam [1.20.1]

### ISSUE THREAD

**Issue by deadspidervenom** [YUNG-GANG/YUNGs-Better-Fortresses#13]
While i appreciate trying to make sure mod pack makers know to report certain things to other mods such as

```
[22:19:04] [DH-World Gen Thread[0]/WARN]: Better Fortresses: Detected a mod with a broken basalt columns configuredfeature that is trying to place blocks outside the 3x3 safe chunk area for features. Find the broken mod and report to them to fix the placement of their basalt columns feature.
```

the amount it spams is causing serious log file sizes (if i got the wrong mod sorry did not see the distant horizions part till now).

```
Stopped watching the game log because the log length surpassed 100000 lines.
You may have to fix your mods because the game is still logging to files and likely wasting harddrive space at an alarming rate!
```

Its to the point where i am earnestly gonna remove better fortresses as i cant see logs for everything else and this last log file is almost 200mb of spam from it.

Perhaps put a repeat delay, so it spits the log out every few minutes.

**Comment by Lethosos** [comment]
This is actually a Mojang issue that has been largely ignored because of certain circumstances. Basically, you're zipping around too fast for the simulation distance to catch up; I had it happen in my pack specifically with The Abyss II while running around in Creative to check the biomes.

**Comment by deadspidervenom** [comment]
> This is actually a Mojang issue that has been largely ignored because of certain circumstances. Basically, you're zipping around too fast for the simulation distance to catch up; I had it happen in my pack specifically with The Abyss II while running around in Creative to check the biomes.

... i was standing still

EDIT: also the log being pushed to the console is the mod, the issue is not what the log is about, but the fact its spamming the message making the log bloated.

**Comment by deadspidervenom** [comment]
> This is actually a Mojang issue that has been largely ignored because of certain circumstances. Basically, you're zipping around too fast for the simulation distance to catch up; I had it happen in my pack specifically with The Abyss II while running around in Creative to check the biomes.

heck i went and found where in the code this occurs.

https://github.com/YUNG-GANG/YUNGs-Better-Fortresses/blob/406f8dc511537c26e96c7807df9495dd7c191960/Common/src/main/java/com/yungnickyoung/minecraft/betterfortresses/mixin/NoBasaltColumnsInStructuresMixin.java#L40

**Comment by deadspidervenom** [comment]
[2024-03-17-5.log.gz](https://github.com/YUNG-GANG/YUNGs-Better-Fortresses/files/14631800/2024-03-17-5.log.gz)
also here is the log in question proving its a issue.

EDIT: its in the zip still due to it being over 100mb unzipped due to the repeated log.

**Comment by yungnickyoung** [comment]
Yikes, sorry about that. I removed the log in the latest versions, v2.0.6 on 1.20.1 and v2.4.2 on 1.20.4.
