### ISSUE TITLE
[Worker-Main-49/WARN]: Ignoring unknown attribute 'forge:entity_gravity' /// [Worker-Main-61/ERROR]: Hanging entity at invalid position: class_2338

### ISSUE THREAD

**Issue by MrBluntmaster** [YUNG-GANG/YUNGs-Better-Fortresses#5]
**Hello, we have a few problems on our server (GPortal, 10gb RAM, fabric1.19.2-0.14.21) with warnings and errors:**

**first the modlist:**
Tectonic/Better Nether/Better End/Chunky/BCLib/YUNG's API/Cloth Config API

**Here is a list of the problems that occur:**

**+YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar**

-[Worker-Main-2/WARN] (class_5131) Ignoring unknown attribute 'forge:entity_gravity

**+YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0**

-clear

**+YungsBetterNetherFortresses-1.19.2-Fabric-1.0.5.jar**

-[Worker-Main-52/WARN]: Ignoring unknown attribute 'forge:entity_gravity'

**+YungsBetterMineshafts-1.19.2-Fabric-3.2.0**

-clear

**+YungsBetterDungeons-1.19.2-Fabric-3.2.1**

-clear

**+YungsBetterDesertTemples-1.19.2-Fabric-2.2.2**

-[Worker-Main-30/WARN]: Ignoring unknown attribute 'forge:entity_gravity'

-[Worker-Main-61/ERROR]: Hanging entity at invalid position: class_2338{x=-207, y=62, z=-262}

does anyone know how I can do this? I've been searching for a while but haven't found anything. Maybe I'm just overlooking something very simple.   Thanks in advance :)

**Comment by yungnickyoung** [comment]
These are essentially just warning logs, but shouldn't cause any issues. Are you seeing any issues wit hthe generated structures?

**Comment by MrBluntmaster** [comment]
no, that was all, damn you are fast :)
The structures are awesome, thanks for that at this point.
only these warnings are spamming while generating.
:)
