### ISSUE TITLE
Create fabric 0.5.1b bug ?

### ISSUE THREAD

**Issue by wanesty** [YUNG-GANG/YUNGs-Better-Fortresses#6]
Better Fortresses doesn't seem to recognize that Create is installed ;
or at least i can't seem to be able to open the main gates.

i tried the button facing them but it does not seem to do anything nor do i see any create blocks below the gates nor anywhere in the structure.

is this actually a bug or am i missing something ?

**Comment by wanesty** [comment]
ahah https://github.com/YUNG-GANG/YUNGs-Better-Fortresses/blob/72fa5ed0d98c8030cce2b11775f548eca94b63a5/Common/src/main/resources/data/betterfortresses/worldgen/template_pool/battle_bridge.json#L54 is it a forge only feature ?

**Comment by NolanHewitt** [comment]
I was wondering the same thing. Changing that text doesn't seem to make it work for fabric sadly.

**Comment by wanesty** [comment]
the file seems to be a declarative config for yung's own api so it would likely also require modification of said api

EDIT : [yungsapi/services/FabricPlatformHelper.java](https://github.com/YUNG-GANG/YUNGs-API/blob/multiloader/1.18/Fabric/src/main/java/com/yungnickyoung/minecraft/yungsapi/services/FabricPlatformHelper.java) maybe one of those I honestly have no idea I'll have to open it in a IDE

**Comment by yungnickyoung** [comment]
Added support for Create in the new release! Check it out, and make sure you have the latest release of Create Fabric when testing. Feel free to close the issue if it's working properly.

**Comment by NolanHewitt** [comment]
It works for me!

**Comment by wanesty** [comment]
can confirm !
also i looked at how the gate work and i'm impressed ahah
