### ISSUE TITLE
[1.20] Armor Trims?

### ISSUE THREAD

**Issue by tesseract-two** [YUNG-GANG/YUNGs-Better-Fortresses#7]
I've looked through the loot tables in the 1.20 branch, and I didn't see any armor trims. Are they part of the structure (item frames etc) or unobtainable in the current version? I've noticed the same in your other mods too. Also, thank you for these awesome redesigns!

**Comment by yungnickyoung** [comment]
Since 1.19.2, all my structures contain chests with all vanilla loot tables, in addition to new custom tables. So all armor trims will be obtainable via the vanilla loot tables

**Comment by tesseract-two** [comment]
Ah, thank you!
