### ISSUE TITLE
Recognising Quilt

### ISSUE THREAD

**Issue by Rellina** [YUNG-GANG/YUNGs-Better-Fortresses#9]
Problem with YungsBetterNetherFortresses, and YungsBetterDessertTemple interaction with Quilt. 

Quilt Loader 0.20.2
![Yung's Error Report](https://github.com/YUNG-GANG/YUNGs-Better-Fortresses/assets/125359933/627884ee-fd6e-417a-9a86-c23b2eba84da)

Crash Report
[crash-2023-09-15_20.54.45.8571-quilt_loader.txt](https://github.com/YUNG-GANG/YUNGs-Better-Fortresses/files/12618763/crash-2023-09-15_20.54.45.8571-quilt_loader.txt)

**Comment by Rellina** [comment]
API enabled.

![Yungs](https://github.com/YUNG-GANG/YUNGs-Better-Fortresses/assets/125359933/88eb45ae-e642-4954-99c3-e0935494fd58)

[crash-2023-09-15_21.31.39.5149-quilt_loader.txt](https://github.com/YUNG-GANG/YUNGs-Better-Fortresses/files/12618873/crash-2023-09-15_21.31.39.5149-quilt_loader.txt)

**Comment by yungnickyoung** [comment]
The error message just says you aren't using a new enough version of YUNG's API. Try using this version instead https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric/files/4441684
